server:
  port: 0
  servlet:
    context-path: /proservice

springdoc:
  swagger-ui:
    path: /swagger

  api-docs:
    path: /api-docs
feign:
  hystrix:
    enabled: true
---
---


logging:
  file:
    path: ./
    name: logfile.log
---
---
servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 15MB


spring:
  application:
    name: product-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
